name: ShotBlog
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAGE }}
          config_timezone: Asia/Shanghai
          
          # 屏幕截图
          filename: blog_status.svg
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          # plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.uichans.com/
